name: NuGet Template Publish

on:
  push:
    tags:
      - "v*"

jobs:
  pack-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Get version from tag
        id: get_version
        run: |
          echo "TAG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update version in nuspec
        run: |
          sed -i "s/<version>.*<\/version>/<version>${TAG_VERSION}<\/version>/" Microservice.Template.nuspec

      - name: Pack NuGet template
        run: nuget pack Microservice.Template.nuspec -OutputDirectory ./nupkg

      - name: Publish to NuGet.org
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
