name: NuGet Template Publish

on:
  push:
    branches:
      - main

jobs:
  pack-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Get current version
        id: get_version
        run: |
          VERSION=$(grep -oP '<version>\K[^<]+' Microservice.Template.nuspec)
          echo "Current version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Bump patch version
        id: bump_version
        run: |
          IFS='.' read -r major minor patch <<< "$VERSION"
          patch=$((patch+1))
          NEW_VERSION="$major.$minor.$patch"
          echo "Bumped version: $NEW_VERSION"
          sed -i "s/<version>.*<\/version>/<version>${NEW_VERSION}<\/version>/" Microservice.Template.nuspec
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit version bump
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Microservice.Template.nuspec
          git commit -m "chore: bump version to $NEW_VERSION" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Install Mono
        run: sudo apt-get update && sudo apt-get install -y mono-complete

      - name: Install NuGet CLI
        run: |
          wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
          sudo mv nuget.exe /usr/local/bin/nuget.exe
          sudo chmod +x /usr/local/bin/nuget.exe
          echo "nuget.exe location:" && ls -l /usr/local/bin/nuget.exe

      - name: Pack NuGet template
        run: mono /usr/local/bin/nuget.exe pack Microservice.Template.nuspec -OutputDirectory ./nupkg

      - name: Publish to NuGet.org
        run: dotnet nuget push ./nupkg/BM.MicroserviceTemplate.NET.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
