name: NuGet Template Publish

on:
  push:
    tags:
      - "v*"

jobs:
  pack-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Get version from tag
        id: get_version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Update version in nuspec
        run: |
          sed -i "s/<version>.*<\/version>/<version>${TAG_VERSION}<\/version>/" Microservice.Template.nuspec

      - name: Install Mono
        run: sudo apt-get update && sudo apt-get install -y mono-complete

      - name: Install NuGet CLI
        run: |
          wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
          sudo mv nuget.exe /usr/local/bin/nuget.exe
          sudo chmod +x /usr/local/bin/nuget.exe
          echo "nuget.exe location:" && ls -l /usr/local/bin/nuget.exe

      - name: List files before pack
        run: ls -l

      - name: Pack NuGet template
        run: mono /usr/local/bin/nuget.exe pack Microservice.Template.nuspec -OutputDirectory ./nupkg

      - name: Publish to NuGet.org
        run: dotnet nuget push ./nupkg/BM.MicroserviceTemplate.NET.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
